title: Nadia Gonzalez Fernandez
description: Nadia's homepage
baseurl: ""
url: https://nala7.github.io/

theme: cvless

# site settings
taglong: Master's Student at Université de Montréal
tagshort: MSc Student
cv: true

# author settings
author:
  name: Nadia Gonzalez Fernandez
  email: nadia.gonzalez.fernandez@umontreal.ca
photo: assets/files/photo.jpeg
joblines:
  - Université de Montréal
  - Faculté des arts et des sciences
  - Département d'informatique et de recherche opérationnelle
  - 3150 Jean Brillant St, Montreal, Quebec H3T 1N8, Canada


# profile links
profile:

  linkedin: https://www.linkedin.com/in/nadia-glez/
  github: https://github.com/nala7

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
